name: Contribution Graph (Gold Theme)

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-graph:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore: update contribution graph')"
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Contribution Graph
        run: curl -o contribution-graph.svg "https://ghchart.rshah.org/F7D34D/jayesh-durge"
      - name: Commit Graph
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update contribution graph"
          file_pattern: contribution-graph.svg
